<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://services.fisheries.mare.ec.europa.eu/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://ec.europa.eu/mare/fisheries/services/mdr/v1" name="MDREndPointService" targetNamespace="http://services.fisheries.mare.ec.europa.eu/">
    <wsdl:import location="http://localhost:8080/MDR-Service-Mock-1.0.1/v1/MDRService?wsdl=MDRService.wsdl" namespace="http://ec.europa.eu/mare/fisheries/services/mdr/v1">
    </wsdl:import>
    <wsdl:binding name="MDREndPointServiceSoapBinding" type="ns1:MDRService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getLatestVersionOfMDRList">
            <soap:operation soapAction="http://ec.europa.eu/mare/fisheries/services/mdr/v1/MDRService/getLatestVersionOfMDRListRequest" style="document"/>
            <wsdl:input name="getLatestVersionOfMDRList">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getLatestVersionOfMDRListResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="MDRServiceFault_Exception">
                <soap:fault name="MDRServiceFault_Exception" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getMDRList">
            <soap:operation soapAction="http://ec.europa.eu/mare/fisheries/services/mdr/v1/MDRService/getMDRListRequest" style="document"/>
            <wsdl:input name="getMDRList">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="getMDRListResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="MDRServiceFault_Exception">
                <soap:fault name="MDRServiceFault_Exception" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MDREndPointService">
        <wsdl:port binding="tns:MDREndPointServiceSoapBinding" name="MDREndPointPort">
            <soap:address location="http://localhost:8080/MDR-Service-Mock-1.0.1/v1/MDRService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>